services:
  php:
    build:
      context: ./docker/php
    platform: linux/amd64
    volumes:
      - .:/var/www/html
      - ./docker/php/database.php.docker:/var/www/html/app/Config/database.php
    expose:
      - 9000
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "cd /var/www/html/app && php Console/cake.php Migrations.migration run all && php-fpm"

  nginx:
    image: nginx:stable
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:5.7
    platform: linux/amd64
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
    restart: always
    environment:
      MYSQL_DATABASE: cakephp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: cake
      MYSQL_PASSWORD: cake
    ports:
      - "3300:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
